# Generated by Django 5.1.4 on 2024-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('fill_in_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('multiple_choice', 'Multiple Choice'), ('audio_question', 'Audio Question')], max_length=20)),
                ('question', models.TextField()),
                ('correct_answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
